version: "3.8"

services:
  nest:
    build: .
    depends_on:
      - redis
      - postgres
      - minio
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=test
      - SECRET_ACCESS=afwsfafawfawfawf
      - SECRET_REFRESH=AFWFSAFsdadasddad
      - MINIO_BUCKET_NAME=mybucket
      - MINIO_ENDPOINT=http://192.168.3.34:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "3000:3000"
    command: npm run start:prod

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports: 
      - "5433:5432"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001" &
    ports:
      - "9000:9000"
      - "9001:9001"
    